"""Canonical semantic annotation domain model (unified contract).

See ``docs/architecture/unified_semantic_contract.md``. This package is the
single source of truth for what a "semantic annotation" is; it must not
import application/orchestration logic (extraction, prediction, review,
API) -- only the reverse.
"""

from services.semantic.models import (
    SCHEMA_VERSION,
    CATALOG_EXACT_MATCH,
    CATALOG_NOT_IN_CATALOG,
    CATALOG_UNKNOWN,
    SCORE_ASSOCIATION_DISTANCE,
    SCORE_CALIBRATED,
    SCORE_DETERMINISTIC,
    SCORE_RAW_MODEL,
    SCORE_RULE_CONFIDENCE,
    CoordinateTransform,
    DrawingLanguageRule,
    EvidenceRecord,
    EvidenceStrength,
    EvidenceType,
    GeometryAssociation,
    GeometryEvidence,
    GeometryProvider,
    Modifier,
    OperationKind,
    OperationRecord,
    ReviewState,
    ReviewStatus,
    ScoreValue,
    SemanticAnnotation,
    SemanticDocument,
    SourceFragment,
    StructuralParse,
    derive_annotation_id,
)

__all__ = [
    "SCHEMA_VERSION",
    "CATALOG_EXACT_MATCH",
    "CATALOG_NOT_IN_CATALOG",
    "CATALOG_UNKNOWN",
    "SCORE_ASSOCIATION_DISTANCE",
    "SCORE_CALIBRATED",
    "SCORE_DETERMINISTIC",
    "SCORE_RAW_MODEL",
    "SCORE_RULE_CONFIDENCE",
    "CoordinateTransform",
    "DrawingLanguageRule",
    "EvidenceRecord",
    "EvidenceStrength",
    "EvidenceType",
    "GeometryAssociation",
    "GeometryEvidence",
    "GeometryProvider",
    "Modifier",
    "OperationKind",
    "OperationRecord",
    "ReviewState",
    "ReviewStatus",
    "ScoreValue",
    "SemanticAnnotation",
    "SemanticDocument",
    "SourceFragment",
    "StructuralParse",
    "derive_annotation_id",
]
