/** Vitest-only stub: avoids opening thousands of @mui/icons-material files (EMFILE). */
import { createElement } from "react";

function IconStub(props) {
  return createElement("span", { "data-mui-icon-stub": "true", ...props });
}

export const AccountTreeOutlined = IconStub;
export const ArrowForwardRounded = IconStub;
export const Brightness4 = IconStub;
export const Brightness7 = IconStub;
export const CancelOutlined = IconStub;
export const CheckCircle = IconStub;
export const CheckCircleOutlined = IconStub;
export const CheckCircleRounded = IconStub;
export const CheckRounded = IconStub;
export const ChevronLeft = IconStub;
export const ChevronRight = IconStub;
export const CloseOutlined = IconStub;
export const CloudUpload = IconStub;
export const CloudUploadOutlined = IconStub;
export const ContentCopyOutlined = IconStub;
export const DashboardOutlined = IconStub;
export const DataObjectOutlined = IconStub;
export const DoneAllOutlined = IconStub;
export const Download = IconStub;
export const DownloadOutlined = IconStub;
export const EditOutlined = IconStub;
export const ErrorOutlineRounded = IconStub;
export const ErrorOutlined = IconStub;
export const ExpandMoreOutlined = IconStub;
export const FactCheckOutlined = IconStub;
export const FileDownloadOutlined = IconStub;
export const FindInPageOutlined = IconStub;
export const HelpOutlined = IconStub;
export const HighlightOffOutlined = IconStub;
export const HubOutlined = IconStub;
export const InboxOutlined = IconStub;
export const LinkOff = IconStub;
export const LinkOutlined = IconStub;
export const ManageSearchOutlined = IconStub;
export const ModelTrainingOutlined = IconStub;
export const PictureAsPdfOutlined = IconStub;
export const PlaceOutlined = IconStub;
export const PlayArrowOutlined = IconStub;
export const PlayArrowRounded = IconStub;
export const RadioButtonUncheckedOutlined = IconStub;
export const RefreshOutlined = IconStub;
export const RefreshRounded = IconStub;
export const RemoveCircleOutlined = IconStub;
export const RestartAltOutlined = IconStub;
export const RuleOutlined = IconStub;
export const ScienceOutlined = IconStub;
export const SearchOutlined = IconStub;
export const SearchRounded = IconStub;
export const SettingsOutlined = IconStub;
export const SpeedRounded = IconStub;
export const SummarizeOutlined = IconStub;
export const TableRowsOutlined = IconStub;
export const TableViewOutlined = IconStub;
export const TimelineOutlined = IconStub;
export const UploadFileOutlined = IconStub;
export const VerifiedOutlined = IconStub;
export const ViewListOutlined = IconStub;
export const VisibilityOutlined = IconStub;
export const WarningAmberOutlined = IconStub;
export const ZoomIn = IconStub;
export const ZoomOut = IconStub;

export default IconStub;
